In [1]:
import numpy as np

print(np.__version__)

2.4.4


In [4]:
import numpy as np

array = np.array([1, 2, 3, 4])

array = array * 2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [11]:
import numpy as np

array = np.array([[[1, 2, 3] , [4, 5, 6]],
                  [[7, 8, 9] , [10, 11, 12]]])

print(array.ndim)
print(array.shape)

print(array[1, 0, 0])

3
(2, 2, 3)
7


In [18]:
import numpy as np

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# print(array.ndim)
# print(array.shape)

# print(array[0 : 3])

# print(array[0 : 4 : 2])

# print(array[:, : 3])

print(array[0 : 2, :3])

[[1 2 3]
 [5 6 7]]


In [19]:
import numpy as np

array = np.array([1, 2, 3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array * 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[ 5 10 15]
