In [1]:
import numpy as np

print(np.__version__)

2.4.4


In [4]:
import numpy as np

array = np.array([1, 2, 3, 4])

array = array * 2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>


In [11]:
import numpy as np

array = np.array([[[1, 2, 3] , [4, 5, 6]],
                  [[7, 8, 9] , [10, 11, 12]]])

print(array.ndim)
print(array.shape)

print(array[1, 0, 0])

3
(2, 2, 3)
7


In [18]:
import numpy as np

array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12], 
                  [13, 14, 15, 16]])

# print(array.ndim)
# print(array.shape)

# print(array[0 : 3])

# print(array[0 : 4 : 2])

# print(array[:, : 3])

print(array[0 : 2, :3])

[[1 2 3]
 [5 6 7]]


In [19]:
import numpy as np

array = np.array([1, 2, 3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array * 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[ 5 10 15]


In [22]:
import numpy as np

array = np.array([1.3, 2.62, 3.99])

print(np.sqrt(array))
print(np.round(array))
print(np.pi)

[1.14017543 1.61864141 1.99749844]
[1. 3. 4.]
3.141592653589793


In [23]:
import numpy as np

radii = np.array([1, 2, 3])

print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [24]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [28]:
import numpy as np

scores = np.array([30, 78, 94, 100, 81])

# print(scores == 100)
# print(scores >= 60)

scores[scores < 40] = 0
print(scores)

[  0  78  94 100  81]


In [30]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[10],
                   [20]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(2, 3)
(2, 1)
[[ 10  20  30]
 [ 80 100 120]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5], 
                  [6, 7, 8, 9, 10]])

# print(np.sum(array))
# print(np.mean(array))
# print(np.min(array))
# print(np.max(array))
# print(np.std(array))
# print(np.var(array))

print(np.sum(array, axis=0)) # get sam by column
print(np.sum(array, axis=1)) # get sum by row

[ 7  9 11 13 15]
[15 40]


In [8]:
import numpy as np

ages = np.array([[13, 42, 50], 
                  [20, 35, 99]])

teen = ages[ages < 18]
young = ages[(ages >= 18) | (ages <= 60)]

print(teen)
print(young)

adult = np.where(ages >= 30, ages, 0)

print(adult)

[13]
[13 42 50 20 35 99]
[[ 0 42 50]
 [ 0 35 99]]


In [16]:
import numpy as np

rng = np.random.default_rng()

print(rng.integers(low=1, high=100, size=3))

print(rng.integers(low=1, high=100, size=(3, 2)))

[51 64 68]
[[ 7 92]
 [49 11]
 [ 3 75]]


In [18]:
import numpy as np

rng = np.random.default_rng(seed=1)

print(rng.integers(low=1, high=100, size=(3, 2)))

[[47 51]
 [75 95]
 [ 4 15]]


In [22]:
import numpy as np

print(np.random.uniform())

print(np.random.uniform(low=-1, high=1, size=3))

print(np.random.uniform(low=-1, high=1, size=(3, 2)))

0.15626718843615317
[0.84011518 0.2497269  0.74240464]
[[-0.89684893 -0.31197062]
 [-0.47313288 -0.00527314]
 [ 0.60635362  0.82411873]]


In [28]:
import numpy as np

rng = np.random.default_rng()

color = np.array(["red", "yellow", "black", "green", "brown"])

# color = rng.choice(color)

# color = rng.choice(color, size=2)

color = rng.choice(color, size=(2, 2))

print(color)

[['black' 'black']
 ['green' 'green']]
